-- DRAFT / UNAPPLIED / DO NOT RUN
-- F10C2 PHASE 1
-- NO DATABASE TARGET AUTHORIZED
-- PAIR: 101_field_test_runs
-- ROLE: ROLLBACK

BEGIN;
DROP TABLE IF EXISTS public.field_test_runs CASCADE;
COMMIT;
