-- DRAFT / UNAPPLIED / DO NOT RUN
-- F10C2 PHASE 1
-- NO DATABASE TARGET AUTHORIZED
-- PAIR: 103_field_test_metrics
-- ROLE: ROLLBACK

BEGIN;
DROP TABLE IF EXISTS public.field_test_metrics CASCADE;
COMMIT;
